export const GOAL_CATEGORIES = [
  "Career & Jobs",
  "Professional Qualification & Certifications",
  "Education & Exams",
  "Language Learning",
  "Finance & Wealth",
  "Business & Entrepreneurship",
  "Health & Fitness",
  "Weight Loss & Body Transformation",
  "Mental Health & Emotional Wellbeing",
  "Habits & Self Discipline",
  "Productivity & Time Management",
  "Communication & Public Speaking",
  "Relationships & Dating",
  "Marriage & Family",
  "Parenting",
  "Spirituality & Religion",
  "Technology & Coding",
  "Creativity & Art",
  "Music & Performance",
  "Content Creation & Personal Branding",
  "Travel & Relocation",
  "Home & Lifestyle",
  "Sports & Athletic Training",
  "Community & Social Impact",
  "Hobbies & Leisure",
] as const;

export type GoalCategory = typeof GOAL_CATEGORIES[number];
